### ISSUE TITLE
R you available for help ? :/ If yes please help.. experimental purpose building error

### ISSUE THREAD

**Issue by Saikatsaha1996** [Thirtybird/YACMiner#5]
![Screenshot_2022-05-21-18-49-25-034_com termux](https://user-images.githubusercontent.com/72664192/169653456-fd1e6202-54b4-47ce-af2b-d0bbd66db3d1.jpg)

**Comment by Thirtybird** [comment]
This project has been abandoned for 8+ years.  I am unable to assist with this codebase

**Comment by Saikatsaha1996** [comment]
> This project has been abandoned for 8+ years. I am unable to assist with this codebase

already build completed thank you.. ,😊
